name: GitHub Pagesへのデプロイ

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/**
      - src/main/

jobs:
  compile:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Node.js v20.8.0
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 20.8.0
          cache: npm
      - name: Install dependent npm modules
        run: npm install
      - name: Compile npm files
        run: ../../../node_modules/.bin/tsc
        working-directory: ./src/npm/ts
      - name: Compile source files
        run: ../../../node_modules/.bin/tsc
        working-directory: ./src/main/ts
      - name: Fix javascript files
        run: node ./src/npm/ts/import_fixer.js
      - name: Remove source files
        run: rm -rf ./src/main/ts
      - name: Upload page artifact
        uses: actions/upload-pages-artifact@v2.0.0
        with:
          path: src/main/

  deploy:
    runs-on: ubuntu-latest
    needs: compile
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2.0.4